### ISSUE TITLE
Just a quick test

### ISSUE THREAD

**Issue by ogredel** [rgocal/Sapphyx_Issue_Tracker#2]
No real issues just a check for ya

-

Device info:
---
<table>
<tr><td>App version</td><td>1.0</td></tr>
<tr><td>App version code</td><td>1</td></tr>
<tr><td>Android build version</td><td>G935PVPS4BQC1</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G935PVPS4BQC1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>hero2qltespr</td></tr>
<tr><td>Device model</td><td>SM-G935P</td></tr>
<tr><td>Device product name</td><td>hero2qltespr</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Beta</td><td>All content, preferences, settings are subject to change.</td></tr>
<tr><td>Private Builds</td><td>true</td></tr>
</table>

**Comment by rgocal** [comment]
All good!
