### ISSUE TITLE
Crashes a lot

### ISSUE THREAD

**Issue by Technologx** [rgocal/Sapphyx_Issue_Tracker#23]
Every time I enter a different setting to change things, the settings app will crash and I have to open it up and go back into the setting. Before it'll let me change things up.

-

Device info:
---
<table>
<tr><td>App version</td><td>1.00.10 beta</td></tr>
<tr><td>App version code</td><td>10</td></tr>
<tr><td>Android build version</td><td>C07B160</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>H1611C07B160</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWH1611-Q</td></tr>
<tr><td>Device model</td><td>H1611</td></tr>
<tr><td>Device product name</td><td>H1611</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Notice</td><td>All content, preferences, settings are subject to change.</td></tr>
<tr><td>Public Beta Builds</td><td>true</td></tr>
</table>

**Comment by rgocal** [comment]
Is this in a specific category or all of them. Try resetting the launcher data. 

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Technologx** [comment]
All of them, I tried installing 3x's and it did the same every time.-------- Original Message --------Subject: Re: [rgocal/Sapphyx_Issue_Tracker] Crashes a lot (#23)From: Ry To: rgocal/Sapphyx_Issue_Tracker CC: Technologx ,Author Is this in a specific category or all of them. Try resetting the launcher data.
Sent from my Xiaomi MI 5 using FastHub

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rgocal/Sapphyx_Issue_Tracker","title":"rgocal/Sapphyx_Issue_Tracker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rgocal/Sapphyx_Issue_Tracker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rgocal in #23: Is this in a specific category or all of them. Try resetting the launcher data. \n\n_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_"}],"action":{"name":"View Issue","url":"https://github.com/rgocal/Sapphyx_Issue_Tracker/issues/23#issuecomment-315789608"}}}

**Comment by rgocal** [comment]
Make sure you copy the log and share it so i can see whats going down

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Technologx** [comment]
It don't show me any logs.-------- Original Message --------Subject: Re: [rgocal/Sapphyx_Issue_Tracker] Crashes a lot (#23)From: Ry To: rgocal/Sapphyx_Issue_Tracker CC: Technologx ,Author Make sure you copy the log and share it so i can see whats going down
Sent from my Xiaomi MI 5 using FastHub

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rgocal/Sapphyx_Issue_Tracker","title":"rgocal/Sapphyx_Issue_Tracker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rgocal/Sapphyx_Issue_Tracker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rgocal in #23: Make sure you copy the log and share it so i can see whats going down\n\n_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_"}],"action":{"name":"View Issue","url":"https://github.com/rgocal/Sapphyx_Issue_Tracker/issues/23#issuecomment-316131279"}}}

**Comment by rgocal** [comment]
Does it crash or close. Check the crash log for anything 

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Technologx** [comment]
It closes goes right to my home screen-------- Original Message --------Subject: Re: [rgocal/Sapphyx_Issue_Tracker] Crashes a lot (#23)From: Ry To: rgocal/Sapphyx_Issue_Tracker CC: Technologx ,Author Does it crash or close. Check the crash log for anything
Sent from my Xiaomi MI 5 using FastHub

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rgocal/Sapphyx_Issue_Tracker","title":"rgocal/Sapphyx_Issue_Tracker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rgocal/Sapphyx_Issue_Tracker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rgocal in #23: Does it crash or close. Check the crash log for anything \n\n_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_"}],"action":{"name":"View Issue","url":"https://github.com/rgocal/Sapphyx_Issue_Tracker/issues/23#issuecomment-316238558"}}}
