### ISSUE TITLE
Edit Icon Names

### ISSUE THREAD

**Issue by jish98** [rgocal/Sapphyx_Issue_Tracker#24]
Not able to rename icons.

Device info:
---
<table>
<tr><td>App version</td><td>1.00.15 beta</td></tr>
<tr><td>App version code</td><td>12</td></tr>
<tr><td>Android build version</td><td>G600FYDDU1BQF1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.G600FYDDU1BQF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>o7prolte</td></tr>
<tr><td>Device model</td><td>SM-G600FY</td></tr>
<tr><td>Device product name</td><td>o7proltedd</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Notice</td><td>All content, preferences, settings are subject to change.</td></tr>
<tr><td>Public Beta Builds</td><td>true</td></tr>
</table>

**Comment by rgocal** [comment]
Renaming icons is kind of buggy at the moment. Once I have some free time and less priorities, il sit down and try to work out the kinks. Renaming should work if the icon is changed and you may get a force close. 

The weather icon is not meant to be updated. Its meant to act as a shortcut provider to google weather. I do not make enough incom to purchase a weather provider key  for everyone 

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jish98** [comment]
Oh okay cool and Thanks for your response!

**Comment by rgocal** [comment]
No problem! 

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
