### ISSUE TITLE
Dock not being displayed

### ISSUE THREAD

**Issue by jish98** [rgocal/Sapphyx_Issue_Tracker#25]
The dock isn't being displayed even when enabled in settings. 

-

Device info:
---
<table>
<tr><td>App version</td><td>1.00.15 beta</td></tr>
<tr><td>App version code</td><td>12</td></tr>
<tr><td>Android build version</td><td>G600FYDDU1BQF1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.G600FYDDU1BQF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>o7prolte</td></tr>
<tr><td>Device model</td><td>SM-G600FY</td></tr>
<tr><td>Device product name</td><td>o7proltedd</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Notice</td><td>All content, preferences, settings are subject to change.</td></tr>
<tr><td>Public Beta Builds</td><td>true</td></tr>
</table>

**Comment by rgocal** [comment]
This is interesting, il keep tabs on this

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
