### ISSUE TITLE
Fingerprint Lock Bugs

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#31]
*Sent by [**purembakhuman@gmail.com**](mailto:purembakhuman@gmail.com)*

Description:
---

When I add Google Chrome, Camera and Adobe Reader to the fingerprint lock, only Adobe Reader asks for it while other apps open without needing the fingerprint authentication. 

Device info:
---
<table>
<tr><td>App version</td><td>1.00.25 beta</td></tr>
<tr><td>App version code</td><td>20</td></tr>
<tr><td>Android build version</td><td>75</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NPN25.137-67</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>potter_n</td></tr>
<tr><td>Device model</td><td>Moto G (5) Plus</td></tr>
<tr><td>Device product name</td><td>potter_n</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Sapphyx Launcher</td><td>true</td></tr>
<tr><td>User Agreement</td><td>The following statment and/or data I provide is true and reliable information to the developer</td></tr>
</table>

**Comment by rgocal** [comment]
Hadn't noticed this... Investigate

**Comment by rgocal** [comment]
Still a current issue in latest build. May have to set these security actions to a single section untill fixed.
