### ISSUE TITLE
Crash when changing homescreen grid size

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#34]
*Sent by [**erayrafet@gmail.com**](mailto:erayrafet@gmail.com)*

Description:
---

Sapphyx crashed after changing homescreen grid size to 3x5.

Device info:
---
<table>
<tr><td>App version</td><td>1.00.25 beta</td></tr>
<tr><td>App version code</td><td>20</td></tr>
<tr><td>Android build version</td><td>C432B398</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>GRA-L09C432B398</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWGRA</td></tr>
<tr><td>Device model</td><td>HUAWEI GRA-L09</td></tr>
<tr><td>Device product name</td><td>GRA-L09</td></tr>
<tr><td>Device hardware name</td><td>hi3635</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Sapphyx Launcher</td><td>true</td></tr>
<tr><td>User Agreement</td><td>The following statment and/or data I provide is true and reliable information to the developer</td></tr>
</table>

**Comment by rgocal** [comment]
Dev Notes: check grid preferences, something isn't right in both drawer and homescreen. May need to implement changes.
