### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#38]
hate this dock feature

Debug info:
 OS Version: 3.4.0-g71abe49(ee0cec63be)
 OS API Level: 25
 Device: hammerhead
 Model (and Product): Nexus 5 (hammerhead)
 BRAND: google
 HARDWARE: hammerhead
 MANUFACTURER: LGE

Extra Info: Sapphyx Launcher Report

**Comment by rgocal** [comment]
Mmm no good. Needs to be more specific in what you dislike and why.  If your talking about the panes, just disable them. Problem solved.
