### ISSUE TITLE
gesture feature not working

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#41]
in spite of saving gestures it doesn't shows under saved gestures nd gestures not working as well

Debug info:
 OS Version: 3.10.61-11234767(A510FXXS4CQH4)
 OS API Level: 24
 Device: a5xelte
 Model (and Product): SM-A510F (a5xeltexx)
 BRAND: samsung
 HARDWARE: samsungexynos7580
 MANUFACTURER: samsung

Extra Info: Sapphyx Launcher Report

**Comment by rgocal** [comment]
I am assuming you mean Sketches. This may be caused by you not enabling the permissions from startup for reading internal memory. May have to add a pre cautionary permission statement dialog.
