### ISSUE TITLE
Launcher drawer doesn't work good

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#42]
when I'm using the app drawer and I want to shut down (scroll down) it doesn't work very well and always get stuck.

Debug info:
 OS Version: 3.4.42-g78767bc(eng.vikrant.20160908.030411)
 OS API Level: 23
 Device: ghost_retail
 Model (and Product): Moto X (zos_ghost)
 BRAND: motorola
 HARDWARE: qcom
 MANUFACTURER: motorola

Extra Info: Sapphyx Launcher Report

**Comment by rgocal** [comment]
This is already aware of. A fix is being looked into. Most likely tye cause is from updating the target sdk to Oreo and breaking the on swipe listener in the dock.
