### ISSUE TITLE
Having troble

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#53]
with the rest and backup bottons not loading but are clickable they just are blank and back up has a problem it fails.text r now widget is gone 

Debug info:
 OS Version: 3.18.31-perf-g4ed01ab-00028-g272748a-dirty(172911703d1c0)
 OS API Level: 24
 Device: lv517
 Model (and Product): LGMP260 (lv517_mpcs_us)
 BRAND: MetroPCS
 HARDWARE: lv517
 MANUFACTURER: LGE

Extra Info: Sapphyx Launcher Report

**Comment by rgocal** [comment]
Need to make sure permissions to external storage for Sapphyx Launcher is enabled. An easy way to tell is restart launchup or check in the android settings permission settings. Without access to storage, those actions will not accurately work.
