### ISSUE TITLE
Cannot move or select apps after putting phone to sleep

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#58]
idk if this will help but the issue happens after every time i put the phone to sleep.  So.  Restart app, move stuff.  Press power once to sleep.  Wake up.  Unlock.  Cant move stuff anymore.

Debug info:
 OS Version: 3.18.31-12623509(G930PVPU5BQL1)
 OS API Level: 24
 Device: heroqltespr
 Model (and Product): SM-G930P (heroqltespr)
 BRAND: samsung
 HARDWARE: qcom
 MANUFACTURER: samsung

Extra Info: Sapphyx Launcher Report

**Comment by rgocal** [comment]
Lets try adding a keep in memory tweak to fix this
