### ISSUE TITLE
Banner doesn't respond consistently

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#69]
I'm Benjamin. Had issue getting tap on banner registered. 
ben.rossington@gmail.com
Let me know what else you need. :)

Debug info:
 OS Version: 3.18.31-perf-geee69a3(91)
 OS API Level: 24
 Device: potter
 Model (and Product): Moto G (5) Plus (potter)
 BRAND: motorola
 HARDWARE: qcom
 MANUFACTURER: motorola

Extra Info: Sapphyx Launcher Report

**Comment by rgocal** [comment]
Is their a compatibility issue here? Lets try replacing the scroll view with a viewpager sometime.

**Comment by rgocal** [comment]
Fixed!
