### ISSUE TITLE
Applied icon pack, no change in home screen

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#70]
Applied icon pack, went back to home screen and saw no change. Entered settings to apply it again, it shows as applied. Tapped and applied it again. Back on home screen, no change still.

Debug info:
 OS Version: 3.18.31-perf-geee69a3(91)
 OS API Level: 24
 Device: potter
 Model (and Product): Moto G (5) Plus (potter)
 BRAND: motorola
 HARDWARE: qcom
 MANUFACTURER: motorola

Extra Info: Sapphyx Launcher Report

**Comment by rgocal** [comment]
Sapphyx Launcher Homescreen ic9ns rely on a cache memory and are not affected by icon changes automatically. Users must change the icons manually through editing or redrag out from the app drawer. This is normal behavior. Whether it be improved on in the future is unknown.
