### ISSUE TITLE
Color malfunction

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#74]
Background colors of app drawer and some other colors will not change. Clicking the option fails to bring up a menu. I have tried restart, uninstall, manually deleting app data. Please help, was working fine and I was really enjoying it. 

Debug info:
 OS Version: 3.10.108-Stock-bhb27-nougat-kerneL(95bcd903a6)
 OS API Level: 25
 Device: quark
 Model (and Product): DROID Turbo (cm_quark)
 BRAND: motorola
 HARDWARE: qcom
 MANUFACTURER: motorola

Extra Info: Sapphyx Launcher Report

**Comment by rgocal** [comment]
This will be fixed in Sapphyx 2.0
