### ISSUE TITLE
Sapphyx on Redmi Note 5 Pro

### ISSUE THREAD

**Issue by PlaidRadish** [rgocal/Sapphyx_Issue_Tracker#83]
Not sure what's causing this, but at the moment, I can't use Sapphyx at all. It crashes on every start. I don't understand the log, so here it is:

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: unexpected url: 
	at okhttp3.Request$Builder.url(Request.java:143)
	at com.prof.rssparser.Parser.doInBackground(Parser.java:63)
	at com.prof.rssparser.Parser.doInBackground(Parser.java:34)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

Ideas?

**Comment by rgocal** [comment]
Unfortunately, the log you captured got nothing of the Sapphyx Launcher crash. Make sure to look for 'com.gsd.sapphyx.launcher'

This is what I like to see tho. Something I can work with and explain the problem.

**Comment by PlaidRadish** [comment]
Oh - weird. It truncated the log. I'll try to get a better log.

**Comment by PlaidRadish** [comment]
I just got this crash when trying to set notification bubble access. I'm guessing it's also unhelpful?

java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.ListView
	at com.miui.internal.variable.Android_Preference_Preference_class.bq(SourceFile:179)
	at com.miui.internal.variable.Android_Preference_Preference_class.bs(Unknown Source:0)
	at com.miui.internal.variable.Android_Preference_Preference_class$1.onCheckedChanged(SourceFile:162)
	at miui.widget.SlidingButton$1$1.run(SourceFile:125)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6600)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Comment by rgocal** [comment]
MIUI is crashing, trying to launch an action that does exist in aosp but doesn't in miui. I had this happen on my Mi 5

**Comment by PlaidRadish** [comment]
OK, so this log was actually helpful, I guess?
What can I do to resolve this? Just try to remember never to tap on the notification bubble settings?

**Comment by rgocal** [comment]
Basically, MIUI has alot of the normal android settings ripped out and replaced with its own implementations. If you enabled bubbles once, it should still be. You can restart your device to see them if they are. I don't remember how to access notification settings in MIUI to check. I believe it would be through android settings

**Comment by PlaidRadish** [comment]
**OK. So that setting in Sapphyx will just crash - no way to fix that. Got it.**

**Back to the log at the top that was truncated - here is the complete log - the crash happened 3 times in a row, and this is all I could get from adb logcat:**

07-08 17:05:33.856 11797 12302 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
07-08 17:05:33.856 11797 12302 E AndroidRuntime: Process: com.gsd.launcher.sapphyx, PID: 11797
07-08 17:05:33.856 11797 12302 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: unexpected url: 
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:143)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at com.prof.rssparser.Parser.doInBackground(Parser.java:63)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at com.prof.rssparser.Parser.doInBackground(Parser.java:34)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-08 17:05:33.856 11797 12302 E AndroidRuntime: 	... 4 more
07-08 17:05:45.298 13075 13774 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
07-08 17:05:45.298 13075 13774 E AndroidRuntime: Process: com.gsd.launcher.sapphyx, PID: 13075
07-08 17:05:45.298 13075 13774 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: unexpected url: 
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:143)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at com.prof.rssparser.Parser.doInBackground(Parser.java:63)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at com.prof.rssparser.Parser.doInBackground(Parser.java:34)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-08 17:05:45.298 13075 13774 E AndroidRuntime: 	... 4 more
07-08 17:06:14.987 15564 15653 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
07-08 17:06:14.987 15564 15653 E AndroidRuntime: Process: com.gsd.launcher.sapphyx, PID: 15564
07-08 17:06:14.987 15564 15653 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: unexpected url: 
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:143)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at com.prof.rssparser.Parser.doInBackground(Parser.java:63)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at com.prof.rssparser.Parser.doInBackground(Parser.java:34)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-08 17:06:14.987 15564 15653 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

**Comment by rgocal** [comment]
Did you change anything in Swiftfeed?

**Comment by PlaidRadish** [comment]
Yes, I removed the Yahoo! news feed and selected the GoCalSD Blog.
When I exit settings, (and if it doesn't crash) I get a blank page from Sapphyx Launcher and I have to swipe left to get back to the launcher home page

**Comment by rgocal** [comment]
Try switching the context page to Search or Calendar

**Comment by PlaidRadish** [comment]
OK, the GocalSD feed page finally worked, but it appears potentially a bit buggy. Sometimes it comes up quickly, other times slowly, and sometimes it crashes. Frustratingly, when it crashes, the phone defaults back to the built-in launcher, resetting my defaults.
Setting it to Search produces the Google search bar at the top and a slightly grayed-out wallpaper.
Setting it to Calendar displays nothing but my wallpaper, slightly grayed out.

*Additionally, changing wallpapers seems to crash Sapphyx, as well. Same results as above on default launcher selection, of course.
