### ISSUE TITLE
Latest Beta updates 

### ISSUE THREAD

**Issue by PlaidRadish** [rgocal/Sapphyx_Issue_Tracker#86]
Loving the new options & tweaks from the beta updates, so far. Looks great!

On most recent reboot, I noticed the widgets take additional 30-60 seconds to load. That behavior didn't seem to exist on the stock launcher. Maybe it can be tweaked in next beta? 

Debug info:
 OS Version: 4.4.78-perf+(V9.5.17.0.OEIMIFA)
 OS API Level: 27
 Device: whyred
 Model (and Product): Redmi Note 5 (whyred)
 BRAND: xiaomi
 HARDWARE: qcom
 MANUFACTURER: Xiaomi

Extra Info: Sapphyx 2WO Report

**Comment by rgocal** [comment]
I've noticed this myself. Making some major changes in the next build and Il see if i can figure this out as apart of the next beta update.
