### ISSUE TITLE
Merry Christmas

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Issue_Tracker#93]
sent $0.99 for Christmas under "feature request" in supportive backing. loving the color themeing you've done so far, let's get rid of more white!

thx for all you do

Debug info:
 OS Version: 3.10.108-Stock-bhb27-Oreo-kernel(74bf5bc062)
 OS API Level: 27
 Device: quark
 Model (and Product): DROID Turbo (rr_quark)
 BRAND: motorola
 HARDWARE: qcom
 MANUFACTURER: motorola

Extra Info: Sapphyx Launcher

**Comment by rgocal** [comment]
Very much appreciated
